spring:
  datasource:
    url: jdbc:postgresql://localhost/harproject?stringtype=unspecified
    username: postgres
    password: 271828

  jpa:
    hibernate:
      ddl-auto: none

    properties.hibernate.jdbc.lob.non_contextual_creation: true
    show-sql: true

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

  servlet:
    multipart:
      max-file-size: 10MB

  rabbitmq:
    host: localhost
    queueName: harQueue

logging:
  level:
    liquibase: INFO
